### ISSUE TITLE
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)

### ISSUE THREAD

**Issue by xueqing0622** [banodoco/Steerable-Motion#15]
my gpu is 3060 12G set 512X768 when in flim vfi error:
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 10.36 GiB
Requested               : 384.00 MiB
Device limit            : 12.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

![image](https://github.com/banodoco/Steerable-Motion/assets/114840118/2ee1fba5-4753-43c8-bf26-078fc64b3e24)

**Comment by peteromallet** [comment]
This actually seems to be with a different node - could you try bipassing that - basically, just plug the frames connection into the next point - and see if it works then? 

You can then switch it out for a different Frame Interpolator - that one causes due to Cupy - maybe try switching to FiLM VFI

Here's the relevant repo for that who may be able to provide more detailed help: https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/issues

**Comment by peteromallet** [comment]
Going to close this for now but let me know if it's still not working
